name: Factions
version: 1.0-SNAPSHOT
main: de.erethon.factions.Factions
api-version: 1.20
depend: [ Aergia ]
softdepend: [ LWC, Bolt ]
authors: [ Fyreum, Malfrador ]
description: A Factions plugin
commands:
  factions:
    aliases:
      - f
    description: Main faction command
